# See: https://courses.mooc.fi/org/uh-cs/courses/devops-with-kubernetes/chapter-3/configuring-applications
apiVersion: v1
data:
    db-password: ENC[AES256_GCM,data:+jEFQKplbxrgCsKb,iv:Dxg/Zt1cAXuBlj2csM1kYHHO4edhKvPyl9EN1wAucAM=,tag:CfyetfCB6Nu+e4fIwEIayA==,type:str]
    db-url: ENC[AES256_GCM,data:xb36Cr3GAWn9d8vCemNdI0waC5mhMXbFOUf9Sgg7Kl4RvDHspWsSVopjR8RpDyQjyA2W9teTWolW1jb+/2mvLXr1LYA=,iv:DfdZJl9tAfejVIcRZb6TjSbBughC/afiWt6+tGy+eKE=,tag:iL7Evj3Tuuvb5AErGRPGrA==,type:str]
kind: Secret
metadata:
    name: todo-app-db-secret
sops:
    age:
        - recipient: age1fmv054w2m9d4gjpjczn3gryjdr0upwt4q4lw7r5ut2jz64a4qynsm82arr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua3ROWHZXYXV6b3kxN3Nu
            SjZiS1c1RVhYditEaHdlZUdkcExqVEgrdlFzCjJOYVBYdE5ySUg0RjZ5dXQ1c1dM
            U2wxUk1PelVhVGdQVHh4a0hhOXh3MGcKLS0tIGVMeUM4Nk85T0IvTlQzVjIrVmlP
            K2RuYWRHQlFLSE1FTkEyUjBCR2M5NGcKNhpP2T1W0008T/Q+ikmx/XL20af+UHyW
            5I5tEr0h/APZewYeYDvTPooIkGFp65rCoQ/n1kkeRPHGAMgnYaTSEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T14:06:15Z"
    mac: ENC[AES256_GCM,data:xTQkEE2lO4llbwHYyj3YJ/5wuaIHyCS1TdDTRxwT1KPhQx3IjcB7ibR2ofYo8HQq2PMg/ZNO1qIXxYLHRpo3Tdex5ikwFy8sVtKQBCgiWD20BQG70RtFR9IX7yfqWlizPT9p6nfD3oCOuzkbYSm0mLjdYcHVfLCcogZ2cShEwxk=,iv:SGY9NTW2wb4UMhd/quYZT8wF99Tx0ksFNeM5g8OIjcE=,tag:svw+N7Lu2nUO0P3M7WVSrg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
