apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: ping-pong-restart-rate
  namespace: exercises
spec:
  metrics:
  - name: ping-pong-restart-rate
    # Failing condition: The CPU usage rate sum for the namespace is greather than 2 over the last 5'
    initialDelay: 2m
    successCondition: result > 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1767-prometheus.prometheus.svc.cluster.local:9090
        query: sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[5m]))
