# See: https://courses.mooc.fi/org/uh-cs/courses/devops-with-kubernetes/chapter-3/configuring-applications
apiVersion: v1
data:
    db-password: ENC[AES256_GCM,data:3xxGwUzNrMn54ytf,iv:TFxksTbV7OtJwgLc/L4qUARHLSvLQQ6P4PtOvSObwbc=,tag:eQ9/ISHDkaF8fYN2J2jsGw==,type:str]
    db-url: ENC[AES256_GCM,data:M+rkW+ldu3899mc4uBE6mRee8Naj6fdeIg8jHfJy1sPfZiR1HzGQG9xpWNvTQbKcv3L8PGIJ5saRr5aGqJS8uYNrUVrO/VMF,iv:oIR98BQXgcOT0y14mlLouGtv9Av8kMyEqUkqxwYg9nY=,tag:ybx4M6TBvHToLYFK3DC32g==,type:str]
kind: Secret
metadata:
    name: ping-pong-db-secret
sops:
    age:
        - recipient: age12mp33asndy86w2uyy7h2cfzr73ct8nmyelhq83aphc33gevw0sxq4k5ffx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveG10WmlGQVJwTnZCVFlN
            KzF6aUk1ZXBUNHFXcDBGRThVbXBCRjBxY2h3CnFIeFdBYkhyVS9sZGhoTVFVNFBJ
            M3lGNk93aUp2Q21EU1RQSG5wNnNwcVEKLS0tIFNDNkFWSEEyNzlxNkVaTjQ0d3lo
            djNFNXFkamNFMUJJc1BsMzZucE5YSUkK9Xvs9DrLz+ja+M7T3oW+Rbcv/Gl89Uc7
            db8snseySEW3jc3Rve4vGr1wh99RWGWFJzibMEbtdqclA7I3GwrqVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T14:08:33Z"
    mac: ENC[AES256_GCM,data:W3Xw0/EqUljbPCFPK8UUKuTcs7UHEnnCU/1a5CdhuqdFjhHZXfmfVWtKxVFfi91NregVL//fLWJJx/KeYw0igH29xuoj2GNbZboIjMfUh8wx1WZOql+fvPNOuOtTNg6vlcAw0bfZxH84CrADqlqx4EUnIvYdhw3/zIiEceK6ZdM=,iv:+RHMWnpk/8JwmQ4Hc+acuWRcqHKFp59m9nnCa0Zgj3c=,tag:Dzszk6DEG+n+XpcUsxfOlg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
