apiVersion: v1
kind: Service
metadata:
  name: ping-pong-cluster-ip
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 5070
      protocol: TCP
      targetPort: 5070
