apiVersion: v1
kind: Service
metadata:
  name: ping-pong-clusterip
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5070
