apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-statefulset
spec:
  serviceName: ping-pong-service
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-container
          image: thespeaker33/ping-pong
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
        - name: ping-pong-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: POSTGRES_DB
              value: ping_pong
          ports:
            - name: database
              containerPort: 5432
          volumeMounts:
            - name: ping-pong-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: ping-pong-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
  labels:
    app: ping-pong-db
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: ping-pong-app
