apiVersion: v1
kind: Service
metadata:
  name: log-output-cluster-ip
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: log-output-app
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
