apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: ENC[AES256_GCM,data:m2GCZ4BeSIzYhMSr,iv:/okwNvO9ZzeeZaXjSScjkuswjWZscRCerz1QoiouNnk=,tag:q9TBfY8P4EmCZZAbJndErg==,type:str]
    #ENC[AES256_GCM,data:CGtgdooGP1n9R2+3AYtqvDWS258dthKhQAQpbAkF6iOvpOSEzHDRL95P3o+KgqhaWH+tEnxwAo8GIxZV2zxAtylbpwMIktMcxRwVAfTZMNI=,iv:fH7IqOV1cwtqMx8KiQ+6vpRL5pEm9JXpx4kxHKm9coQ=,tag:uNiyha8/5TH94oHg4SZiGg==,type:comment]
    #ENC[AES256_GCM,data:RiX/VYPhnvqO4H/vUK7BAa5SSUDb+YlAnvtpgQaEptJytPSzCzahKeuim8BsMoZiP02ptF/KjsUM,iv:Soo0JVP1/iC+LzKNB5Mmx5dRlizOM3lAFZdiVfyGC8I=,tag:kQOLo/HWVC9fnE7qW6f1kA==,type:comment]
sops:
    age:
        - recipient: age17mgq9ygh23q0cr00mjn0dfn8msak0apdy0ymjv5k50qzy75zmfkqzjdam4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzB6WnJXZGdFUks3MGNz
            a2JvNXdOMGxPVDRUTkNyQXE4Wm53Nng5WkI4CnNkOURselg1RWQvTGt0ckJuTFB1
            b2grWi9UZDYrbW1zV0o5UGRRRzhBSmsKLS0tIHhKbzdQTGM1Z1h0Q3puSjQ4ZTZl
            Y0pZN3dQbUJFS09kczVESXVrU1JxeHcKyGpPYulHctlD2mQMCnuaqMNyNilDaI9R
            ofobIL7X36VeVfCY8ZPT/CV95OeCtM8/cDrRKgCXn2no7kmXnu1hcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T14:20:50Z"
    mac: ENC[AES256_GCM,data:mWZAxx5PwF1y/A8wR3Xoz+ILW5xsmUn4X7gNrXYWJ6RqF7bHhNyWAENbIB+iU432xXf4Xpg2RIu9k92XYCJoOa7CHdyzQ8PlSJd1+DqC8MVzFg4PrWC8f0OOyd6a8fHbrbO2PBS+uPRjtu5i4B3+hY+PqlOWP6UmtUgxpIfwwao=,iv:9YBTPDlZkw2aUq9kiWQc4PzOrGG3168b/SdHkG5EV+k=,tag:jaApnsl2xdBslCUrvPsNmQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
