apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
data:
  configuration: |
    api_todo=/todos
    base_pathname=/
    base_url=http://localhost
    health=/healthz
    host=0.0.0.0
    max_requests=100
    window=900000
    wiki_random=https://en.wikipedia.org/wiki/Special:Random
