apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app
  namespace: project
data:
  configuration: |
    api_todo=/todos
    base_pathname=/
    base_url=http://localhost
    host=0.0.0.0
    max_requests=100
    window="15 * 60 * 1000"
