apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-app-db-dump
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dwk-sa
          containers:
          - name: db-dump
            image: google/cloud-sdk:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-db-secret
                  key: POSTGRES_PASSWORD
            - name: PGHOST
              value: todo-app-service
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: todo_app
            command:
            - /bin/sh
            - -c
            - >-
              DATE=$(date +%Y%m%d%H%M%S)
              DUMP="/tmp/todo-app-db-${DATE}.dump"

              pg_dump -Fc > "${DUMP}"
              gcloud storage cp "${DUMP}" "gs://todo-app-storage-bucket/backups/$(basename "${DUMP}")"
          restartPolicy: OnFailure
