apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: todo-app-healthcheck
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 4000
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: todo-app-clusterip
