apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - service-cluster-ip.yaml
  - healthcheckpolicy.yaml
  - route.yaml
  - gateway.yaml
  - horizontalpodautoscaler.yaml
  - poddisruptionbudget.yaml
  - cronjob.yaml
  - cronjob.dump.yaml
