apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - configmap.yaml
  - statefulset.yaml
  - service-cluster-ip.yaml
  - route.yaml
  - gateway.yaml
  - cronjob.yaml
