# Sets limits for all the namespace pod containers
apiVersion: v1
kind: LimitRange
metadata:
  name: todo-app-limit-range
spec:
  limits:
  - default:
      cpu: "15m"
      memory: "150Mi"
    defaultRequest:
      cpu: "10m"
      memory: "100Mi"
    max:
      cpu: "1"
      memory: "15Mi"
    min:
      cpu: "10m"
      memory: "100Mi"
    type: Container
