# Sets limits for all the namespace pod containers
apiVersion: v1
kind: LimitRange
metadata:
  name: todo-app-limit-range
spec:
  limits:
  - default:
      cpu: "100m"
      memory: "150Mi"
    defaultRequest:
      cpu: "20m"
      memory: "80Mi"
    max:
      cpu: "100m"
      memory: "150Mi"
    min:
      cpu: "20m"
      memory: "80Mi"
    type: Container
