apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
spec:
  containers:
    - name: todo-app-container
      image: thespeaker33/todo-app
      env:
        - name: CONFIGURATION
          valueFrom:
            configMapKeyRef:
              name: todo-app-configmap
              key: configuration
      volumeMounts:
      - name: todo-app-volume
        mountPath: "/usr/src/app/files"
        readOnly: true
  volumes:
  - name: todo-app-volume
    configMap:
      name: todo-app-configmap
      items:
      - key: "configuration"
        path: "configuration"
