# Set resources/limits at namespace level
apiVersion: v1
kind: ResourceQuota
metadata:
  name: todo-app-resource-quotas
spec:
  hard:
    # Values are considered as total (combined)
    requests.cpu: "10m"
    requests.memory: "100Mi"
    limits.cpu: "15m"
    limits.memory: "150Mi"
    # Services / Configurations are configurable as well
    configmaps: "1"
    persistentvolumeclaims: "1"
    pods: "1"
    replicationcontrollers: "1"
    secrets: "1"
    services: "2"
    services.loadbalancers: "1"
