apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-statefulset
spec:
  serviceName: todo-app-clusterip
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app-container
          image: thespeaker33/todo-app:latest
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-app-db-secret
                  key: db-url
          # Sets the ready status on the container POD in order to allow income traffic
          readinessProbe:
            httpGet:
              # Specify the healthcheck route
              path: /healthz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Checks the container status and configure how the app should be restarted after an issue
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
        - name: todo-app-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-db-secret
                  key: db-password
            - name: POSTGRES_DB
              value: todo_app
          ports:
            - name: database
              containerPort: 5432
          volumeMounts:
            - name: todo-app-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
  volumeClaimTemplates:
    - metadata:
        name: todo-app-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app-db
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: todo-app
