apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-app-statefulset
spec:
  serviceName: todo-app-clusterip
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      strategy:
        type: Recreate
      containers:
        - name: todo-app-container
          image: thespeaker33/todo-app
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-app-db-secret
                  key: db-url
        - name: todo-app-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-app-db-secret
                  key: db-password
            - name: POSTGRES_DB
              value: todo_app
          ports:
            - name: database
              containerPort: 5432
          volumeMounts:
            - name: todo-app-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: todo-app-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  labels:
    app: todo-app-db
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: todo-app
