apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-ping-pong
  template:
    metadata:
      labels:
        app: log-output-ping-pong
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-volume
      containers:
        - name: log-output-getter
          image: thespeaker33/log-output-getter:latest
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/files
        - name: ping-pong
          image: thespeaker33/ping-pong:latest
          volumeMounts:
          - name: shared-volume
            mountPath: /usr/src/app/files
