apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
  - ../ping-pong/manifests/
  - ../log-output/manifests/
  - statefulset.shared.yaml
  - persistentVolume.shared.yaml
  - persistentVolumeClaim.shared.yaml
  - service-nodeport.shared.yaml
  - service-ingress-shared.yaml
