apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
  namespace: exercises
spec:
  storageClassName: shared-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
