apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-ping-pong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-ping-pong-app
  template:
    metadata:
      labels:
        app: log-output-ping-pong-app
    spec:
      containers:
        - name: log-output-getter-container
          image: thespeaker33/log-output-getter:latest
        - name: ping-pong-container
          image: thespeaker33/ping-pong:latest
