apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ping-pong-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: log-output-nodeport
            port:
              number: 5000
      - path: /pingpong
        pathType: Prefix
        backend:
          service:
            name: ping-pong-nodeport
            port:
              number: 5070
