apiVersion: v1
kind: Service
metadata:
  name: ping-pong-nodeport
spec:
  type: NodePort
  selector:
    app: log-output-ping-pong-app
  ports:
    - port: 5070
      protocol: TCP
      targetPort: 5070
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-nodeport
spec:
  type: NodePort
  selector:
    app: log-output-ping-pong-app
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
