apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: log-output-ping-pong-statefulset
spec:
  serviceName: log-output-ping-pong-service
  replicas: 1
  selector:
    matchLabels:
      app: log-output-ping-pong-app
  template:
    metadata:
      labels:
        app: log-output-ping-pong-app
    spec:
      containers:
        - name: log-output-container
          image: thespeaker33/log-output
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-configmap
                key: message
          volumeMounts:
          - name: shared-temp-volume
            mountPath: /usr/src/app/files
          - name: log-output-volume
            mountPath: /usr/src/app/files/information.txt
            subPath: information.txt
            readOnly: true
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
        - name: ping-pong-container
          image: thespeaker33/ping-pong
          volumeMounts:
          - name: shared-temp-volume
            mountPath: /usr/src/app/files
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ping-pong-db-secret
                  key: db-url
          readinessProbe:
            httpGet:
              path: /pings
              port: 5070
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
        - name: ping-pong-db
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ping-pong-db-secret
                  key: db-password
            - name: POSTGRES_DB
              value: ping_pong
          ports:
            - name: database
              containerPort: 5432
          volumeMounts:
            - name: ping-pong-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: shared-temp-volume
          persistentVolumeClaim:
            claimName: shared-volume
        - name: log-output-volume
          configMap:
            name: log-output-configmap
            items:
            - key: "information.txt"
              path: "information.txt"
  volumeClaimTemplates:
    - metadata:
        name: ping-pong-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-ping-pong-service
  labels:
    app: ping-pong-db
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: log-output-ping-pong-app
