apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
data:
  API_TODO: "/todos"
  BASE_PATHNAME: "/"
  BASE_URL: "http://localhost"
  HEALTH: "/healthz"
  HOST: "0.0.0.0"
  MAX_REQUEST: "100"
  NATS_TIMEOUT: "10000"
  NATS_URL: "nats://localhost"
  WINDOW: "900000"
  WIKI_RANDOM: "https://en.wikipedia.org/wiki/Special:Random"
  PORT: "4000"
  PORT_NATS: "4222"
