# Set resources/limits at namespace level
apiVersion: v1
kind: ResourceQuota
metadata:
  name: todo-app-resource-quotas
spec:
  hard:
    # Values are considered as total (combined)
    requests.cpu: "200m"
    requests.memory: "200Mi"
    limits.cpu: "400m"
    limits.memory: "400Mi"
    # Services / Configurations are configurable as well
    # Setting one or more than the actual requirements - i.e. configmaps, secrets, services, etc. - in order to support K8s automated substitution process
    # Where the new is being added to the old one prior to remove it
    # Recommendation: Being strict with storage objects - volumes, etc. - being large with count-based - svc, pods, configs, secrets, etc.
    configmaps: "2"
    persistentvolumeclaims: "2"
    pods: "2"
    replicationcontrollers: "1"
    secrets: "2"
    services: "4"
    services.loadbalancers: "1"
