kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["stable.dwk"]
  resources: ["dummysites"]
  verbs: ["get", "list", "watch"]
