apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysite.stable.dwk
spec:
  group: stable.dwk
  scope: Namespaced
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
    - ds
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
                image:
                  type: string
      additionalPrinterColumns:
        - name: Website_Url
          type: string
          description: The URL to be copied
          jsonPath: .spec.website_url
