apiVersion: networking.k8s.io/v1
# Handles routing to forward newtork to a Service from a Load Balancer to the Cluster just like a Reverse Proxy
kind: Ingress
metadata:
  name: dwk-material-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hashresponse-svc
            port:
              number: 2345
