# Istio HTTPRoute for Wikipedia Reader app
# Routes traffic to the Wikipedia Reader service
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wikipedia-reader-ingress
  namespace: exercises
spec:
  parentRefs:
    - group: ''
      kind: Service
      name: wikipedia-reader-service
      port: 80
  rules:
    - backendRefs:
        - name: wikipedia-reader-service
          port: 80
