apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
patches:
  - path: statefulset.yaml
namePrefix: staging-
images:
  - name: PROJECT/IMAGE
    newName: thespeaker33/todo-app-staging
