apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base
- cronjob.dump.yaml
patches:
  - path: statefulset.yaml
namePrefix: prod-
images:
  - name: PROJECT/IMAGE
    newName: thespeaker33/todo-app-production
