name: Release application TODO
on:
  push:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: dwk
  IMAGE: todo-app
  SERVICE: todo-app-statefulset
  BRANCH: ${{ github.ref_name }}
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
      - name: 'Use gcloud CLI'
        run: gcloud info && gcloud auth configure-docker europe-north1-docker.pkg.dev --quiet
      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'
      - name : 'Form the image name'
        run: echo "IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/$IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build
        run: cd todo-app && docker build --tag $IMAGE_TAG --build-arg API_TODO=/todos --build-arg BASE_PATHNAME=/ --build-arg BASE_URL=http://localhost --build-arg HOST=0.0.0.0 --build-arg MAX_REQUETS=100 --build-arg PORT=4000 --build-arg WINDOW="15 * 60 * 1000"    --build-arg WIKI_RANDOM="https://en.wikipedia.org/wiki/Special:Random" --build-arg DATABASE_URL="${{ secrets.DB_URL }}" .
      - name: Publish
        run: cd todo-app && docker push $IMAGE_TAG
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
      - name: Set up SOPS
        run: |-
          # Download the SOPS binary
          curl -LO https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.amd64
          # Move the binary in to PATH
          mv sops-v3.11.0.linux.amd64 /usr/local/bin/sops
          # Make the binary executable
          chmod +x /usr/local/bin/sops
      - name: Setup Age
        run: sudo apt install -y age
      - name: Decrypt secrets
        run: |-
          cd todo-app/manifests
          touch age-key.txt
          echo "${{ secrets.AGE_KEY }}" > age-key.txt
          export SOPS_AGE_KEY_FILE=$(pwd)/age-key.txt
          sops --decrypt --ignore-mac secret.enc.yaml > secret.yaml
      - name: Deploy
        run: |-
          cd todo-app/manifests

          echo $([ "$GITHUB_REF" == *"main"* ] && echo "project" || echo "${GITHUB_REF#refs/heads/}")
          echo "[ "$GITHUB_REF" == *"main"* ]"
          echo "[ "${GITHUB_REF}" == *"main"* ]"

          # Updates from main branch must be set as 'project'
          NAMESPACE=$([ "$GITHUB_REF" == *"main"* ] && echo "project" || echo "${GITHUB_REF#refs/heads/}")

          # Create namespace from branchname if not exists
          kubectl create namespace $NAMESPACE || true
          # Set the context to the new branch
          kubectl config set-context --current --namespace=$NAMESPACE
          # Set the new namespace
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image PROJECT/IMAGE=$IMAGE_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout status statefulset $SERVICE
          kubectl get services -o wide
